<?php

namespace App\GenericTableModels;

use Illuminate\Database\Eloquent\Model;
use App\Custom\ModelHelper;

class bondfnb extends Model
{

    protected $primaryKey = 'MatterID';
    protected $table = 'BondFNB';
    protected $connection = 'sqlsrv';
    public $timestamps = false;
    public $incrementing = false;
    protected $fillable = [
							'matterid',
							'email',
							'name',
							'number',
							'insureamount',
							'initiationfee',
							'adminfee',
							'assessmentfee',
							'dateofinterest',
							'completedby',
							'periodofloan',
							'minimum1',
							'minimum2',
							'maximum2',
							'minimum3',
							'maximum3',
							'interestrate1',
							'interestrate2',
							'interestrate3',
							'scheduleb',
							'directors',
							'purchaseprice',
							'purchasedate',
							'titleconditions',
							'furtherbond',
							'specialinstructions',
							'ratespaid',
							'companyformalities',
							'housingclause',
							'maximumamount',
							'employer',
							'rententionamount',
							'embedins',
							'fixedratepercent',
							'rateperiod',
							'totalfinancecharges',
							'contractprice',
							'facilityinitavail',
							'loanvalueperc',
							'transferfees',
							'bankrefname',
							'salesconsultantphone',
							'salesconsultant',
							'salessource',
							'accountname',
							'rateterms',
							'adminfeepaidby',
							'initiationfeepaidby',
							'transfercostspaidby',
							'transactionfee',
							'registrationcosts',
							'registrationcostspaidby',
							'branchbondedto',
							'bankrefname2',
							'propertyrights',
							'suretyamount',
							'suretyrequiredby',
							'maximum1',
							'loantype',
							'instemailaddress',
							'futureuseamount',
							'calconeaccservfeeplustransactionfee',
							'bankrefphone',
							'totalinterestcharged',
							'bondplusamount',
							'totalrepaymentcapitalinterestandallcharges',
							'deferredinitiationfee',
							'amountinsured',
							'calconeaccfacilitylessinitiation',
							'policynumber',
							'totalloanamount',
							'additionalfees',
							'insurancepremium',
							'calcbuildingloanlesscontractamount',
							'grossworkincome',
							'nettworkincome',
							'rentincome',
							'dividendincome',
							'interestincome',
							'totalnonworkincome',
							'livingexpenses',
							'disposableincome',
							'bondrepayment',
							'nettdisposableincome',
							'householdsize',
							'monthlypremium',
							'insurername',
							'insurancecost',
							'furtheramount',
							'outsuranceflag',
							'staffmember',
							'bankreffax',
							'bankaddress_e',
							'valuationamount',
							'currentbal',
							'valuationfee',
							'interesttype',
							'employeenumber',
							'salaryincrease',
							'percentagesalarytoincome',
							'deposit',
							'primerate',
							'monthlyservicefee',
							'totalcostsofagreement',
							'totalinterestfeesandcharges',
							'totalmonthlyinstallment',
							'attorneyinitiationfeetocollect',
							'cpi',
							'minimumcpi',
							'maximumcpi',
							'creditprovidermasterreference',
							'creditproviderncrnumber',
							'creditproviderbankaccountname',
							'creditproviderbankbranch',
							'creditproviderbranchcode',
							'creditproviderbankaccountnumber',
							'creditproviderreferencenumber',
							'initiationexfee',
							'margininterestrate',
							'totalservicefee',
							'primaryconsumergrosssalary',
							'secondareconsumergrosssalary',
							'totalconsumergrosssalary',
							'hoctotalpremium',
							'replacementvalue',
							'primaryconsumersalaryincreasedate',
							'secondconsumersalaryincreasedate',
							'embeddedplan',
							'grantdate',
							'valuationfeepaidby',
							'bondcostspaidby',
							'debitorderdate',
							'totalinterestamount',
							'producttype',
							'fringebenefitamount',
							'totalprincipaldebt',
							'fifthanniversaryinterestamount',
							'sixthanniversaryinterestamount',
							'seventhanniversaryinterestamount',
							'maximumextendedterm',
							'fifthanniversaryservicefee',
							'sixthanniversaryservicefee',
							'seventhanniversaryservicefee',
							'fifthanniversarytotalfees',
							'sixthanniversarytotalfees',
							'seventhanniversarytotalfees',
							'fifthanniversarytotaldebtandfees',
							'primaryconsumerretirementage',
							'newcreditprovider',
							'sixthanniversarytotaldebtandfees',
							'seventhanniversarytotaldebtandfees',
							'capitalisedinitiation',
							'capitalisedfringebenefit',
							'documentversionnumber',
							'lifeassurancetotalamount',
							'flexiaccountnumber',
							'flexibankname',
							'flexibranchcode',
							'flexibranchname',
							'flexiaccountholder',
							'branchbankrefname',
							'branchpostaladdress',
							'branchdocsreturnaddress'
    ];

	public function setdateAttribute($value)
	{
		$this->attributes['date'] = $value ? (String)ModelHelper::convertClarionDate($value) : '';
	}

	public function setcreateddateAttribute($value)
	{
		$this->attributes['createddate'] = $value ? (String)ModelHelper::convertClarionDate($value) : '';
	}

}
        
