<?php

namespace App\GenericTableModels;

use App\Custom\ModelHelper;
use Illuminate\Database\Eloquent\Model;

class empdisplaysettings extends Model
{
    protected $primaryKey = 'EmployeeID';

    protected $table = 'EmpDisplaySettings';

    protected $connection = 'sqlsrv';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = [
        'employeeid',
        'desktopmattercolumn1',
        'desktopmattercolumn2',
        'desktopmattercolumn3',
        'desktopmattercolumn4',
        'desktopmattercolumn5',
        'desktopmattercolumn6',
        'desktopmattercolumn7',
        'desktopmattercolumn8',
        'desktopmattercolumn9',
        'desktopmattercolumn10',
        'desktopmattercolumn11',
        'desktopmattercolumn12',
        'desktopmattercolumn13',
        'desktopmattercolumn14',
        'desktopmattercolumn15',
        'desktopfeenotecolumn1',
        'desktopfeenotecolumn2',
        'desktopfeenotecolumn3',
        'desktopfeenotecolumn4',
        'desktopfeenotecolumn5',
        'desktopfeenotecolumn6',
        'desktopfeenotecolumn7',
        'desktopfeenotecolumn8',
        'desktopfeenotecolumn9',
        'desktopfeenotecolumn10',
        'desktopfeenotecolumn11',
        'desktopfeenotecolumn12',
        'desktopfeenotecolumn13',
        'desktopfeenotecolumn14',
        'desktopfeenotecolumn15',
        'desktopfeenotecolumn16',
        'desktopfeenotecolumn17',
        'desktopfeenotecolumn18',
        'desktopfeenotecolumn19',
        'desktopfeenotecolumn20',
        'desktopfilenotecolumn1',
        'desktopfilenotecolumn2',
        'desktopfilenotecolumn3',
        'desktopfilenotecolumn4',
        'desktopfilenotecolumn5',
        'desktopfilenotecolumn6',
        'desktopfilenotecolumn7',
        'desktopfilenotecolumn8',
        'desktopfilenotecolumn9',
        'desktopfilenotecolumn10',
        'desktopfilenotecolumn11',
        'desktopfilenotecolumn12',
        'desktopfilenotecolumn13',
        'desktopfilenotecolumn14',
        'desktopfilenotecolumn15',
        'desktopremindercolumn1',
        'desktopremindercolumn2',
        'desktopremindercolumn3',
        'desktopremindercolumn4',
        'desktopremindercolumn5',
        'desktopremindercolumn6',
        'desktopremindercolumn7',
        'desktopremindercolumn8',
        'desktopremindercolumn9',
        'desktopremindercolumn10',
        'desktopremindercolumn11',
        'desktopremindercolumn12',
        'desktopremindercolumn13',
        'desktopremindercolumn14',
        'desktopremindercolumn15',
        'desktopmatactivcolumn1',
        'desktopmatactivcolumn2',
        'desktopmatactivcolumn3',
        'desktopmatactivcolumn4',
        'desktopmatactivcolumn5',
        'desktopmatactivcolumn6',
        'desktopmatactivcolumn7',
        'desktopmatactivcolumn8',
        'desktopmatactivcolumn9',
        'desktopmatactivcolumn10',
        'desktopmatactivcolumn11',
        'desktopmatactivcolumn12',
        'desktopmatactivcolumn13',
        'desktopmatactivcolumn14',
        'desktopmatactivcolumn15',
        'desktopdatalinkcolumn1',
        'desktopdatalinkcolumn2',
        'desktopdatalinkcolumn3',
        'desktopdatalinkcolumn4',
        'desktopdatalinkcolumn5',
        'desktopdatalinkcolumn6',
        'desktopdatalinkcolumn7',
        'desktopdatalinkcolumn8',
        'desktopdatalinkcolumn9',
        'desktopdatalinkcolumn10',
        'desktopdatalinkcolumn11',
        'desktopdatalinkcolumn12',
        'desktopdatalinkcolumn13',
        'desktopdatalinkcolumn14',
        'desktopdatalinkcolumn15',
        'addressbookcolumn1',
        'addressbookcolumn2',
        'addressbookcolumn3',
        'addressbookcolumn4',
        'addressbookcolumn5',
        'addressbookcolumn6',
        'addressbookcolumn7',
        'addressbookcolumn8',
        'addressbookcolumn9',
        'addressbookcolumn10',
        'addressbookcolumn11',
        'addressbookcolumn12',
        'addressbookcolumn13',
        'addressbookcolumn14',
        'addressbookcolumn15',
        'doclogcolumn1',
        'doclogcolumn2',
        'doclogcolumn3',
        'doclogcolumn4',
        'doclogcolumn5',
        'doclogcolumn6',
        'doclogcolumn7',
        'doclogcolumn8',
        'doclogcolumn9',
        'doclogcolumn10',
        'doclogcolumn11',
        'doclogcolumn12',
        'doclogcolumn13',
        'doclogcolumn14',
        'doclogcolumn15',
        'desktopremindercolumn16',
        'desktopremindercolumn17',
        'lawlinkcolumn1',
        'lawlinkcolumn2',
        'lawlinkcolumn3',
        'lawlinkcolumn4',
        'lawlinkcolumn5',
        'lawlinkcolumn6',
        'lawlinkcolumn7',
        'lawlinkcolumn8',
        'lawlinkcolumn9',
        'lawlinkcolumn10',
        'lawlinkcolumn11',
        'lawlinkcolumn12',
        'lawlinkcolumn13',
        'lawlinkcolumn14',
        'lawlinkcolumn15',
        'lawlinkcolumn16',
        'lawlinkcolumn17',
        'lawlinkcolumn18',
        'lawlinkcolumn19',
        'lawlinkcolumn20',
        'desktopmattercolumn16',
        'displaylargeiconsflag',
        'activeflag',
        'desktopmattercolumn17',
        'desktopmattercolumn18',
        'desktopmattercolumn19',
    ];

    public function setdateAttribute($value)
    {
        $this->attributes['date'] = $value ? (string) ModelHelper::convertClarionDate($value) : '';
    }

    public function setcreateddateAttribute($value)
    {
        $this->attributes['createddate'] = $value ? (string) ModelHelper::convertClarionDate($value) : '';
    }
}
