<?php

namespace App\GenericTableModels;

use Illuminate\Database\Eloquent\Model;
use App\Custom\ModelHelper;

class reportemp extends Model
{

    protected $primaryKey = 'RecordId';
    protected $table = 'ReportEmp';
    protected $connection = 'sqlsrv';
    public $timestamps = false;
    public $incrementing = true;
    protected $fillable = [
							'recordid',
							'reportemployeeid',
							'reportid',
							'lastused',
							'outputdevice',
							'clientoption',
							'clientid',
							'matteroption',
							'matterid',
							'archiveflag',
							'businessoption',
							'businessid',
							'creditoroption',
							'creditorid',
							'employeeoption',
							'employeeid',
							'costcentreoption',
							'costcentreid',
							'partyoption',
							'partyid',
							'mattertypeoption',
							'mattertypeid',
							'roleoption',
							'roleid',
							'groupoption',
							'groupid',
							'docgenoption',
							'docgenid',
							'transactiondateoption',
							'fromtransactiondate',
							'totransactiondate',
							'instructeddateoption',
							'frominstructeddate',
							'toinstructeddate',
							'periodoption',
							'fromperiod',
							'fromyear',
							'toperiod',
							'toyear',
							'asatperiodoption',
							'asatperiod',
							'asatyear',
							'asatdateoption',
							'asatdate',
							'feesheetoption',
							'feesheetid',
							'feecodeoption',
							'feecodeid',
							'partytypeoption',
							'partytypeid',
							'stageoption',
							'stageid',
							'batchoption',
							'frombatchid',
							'tobatchid',
							'balanceamountoption',
							'balancezeroflag',
							'balanceamount',
							'frombalanceamount',
							'tobalanceamount',
							'transactionamountoption',
							'transactionzeroflag',
							'fromtransactionamount',
							'totransactionamount',
							'actualamountoption',
							'actualzeroflag',
							'fromactualamount',
							'toactualamount',
							'reservedamountoption',
							'reservedzeroflag',
							'fromreservedamount',
							'toreservedamount',
							'investedamountoption',
							'investedzeroflag',
							'frominvestedamount',
							'toinvestedamount',
							'agingoption',
							'agingoverdueby',
							'batchedamountoption',
							'batchedzeroflag',
							'frombatchedamount',
							'tobatchedamount',
							'incomeamountoption',
							'incomezeroflag',
							'fromincomeamount',
							'fromexpenseamount',
							'expenseamountoption',
							'expensezeroflag',
							'toincomeamount',
							'toexpenseamount',
							'descriptionoption',
							'fromdescription',
							'todescription',
							'sheriffareaoption',
							'sheriffareaid',
							'languageoption',
							'languageid',
							'invoiceoption',
							'frominvoiceno',
							'toinvoiceno',
							'statementflag',
							'reconoption',
							'reconciledflag',
							'unreconciledflag',
							'receiptsflag',
							'paymentsflag',
							'otherflag',
							'multipleflag',
							'partialflag',
							'customoption',
							'custom',
							'frommatter',
							'tomatter',
							'zerobalanceoption',
							'zerobalanceflag',
							'outputfilename',
							'defaultgroupoption',
							'defaultgroupid',
							'postingoption',
							'frompostingid',
							'topostingid',
							'branchoption',
							'branchid',
							'remitoption',
							'fromremitno',
							'toremitno',
							'invoicedateoption',
							'frominvoicedate',
							'toinvoicedate',
							'remitdateoption',
							'fromremitdate',
							'toremitdate',
							'customdateoption',
							'fromcustomdate',
							'tocustomdate',
							'group1option',
							'group1id',
							'group2option',
							'group2id',
							'group3option',
							'group3id',
							'assetregoption',
							'assetregid',
							'distributionoption',
							'distributionid',
							'feenoteoption',
							'feenoteid',
							'filenoteoption',
							'filenoteid',
							'todonoteoption',
							'todonoteid',
							'doclogoption',
							'doclogid',
							'coldebitoption',
							'coldebitid',
							'voucheroption',
							'fromvoucher',
							'tovoucher',
							'nextinstallmentdateoption',
							'fromnextinstallmentdate',
							'tonextinstallmentdate',
							'lastinstallmentdateoption',
							'fromlastinstallmentdate',
							'tolastinstallmentdate',
							'outstandingamountoption',
							'fromoutstandingamount',
							'tooutstandingamount',
							'departmentoption',
							'departmentid',
							'todogroupoption',
							'todogroupid',
							'stagegroupoption',
							'stagegroupid',
							'distributiongroupoption',
							'distributiongroup',
							'vatoption',
							'emailoption',
							'fromemaildate',
							'toemaildate',
							'transactioncostcentreoption',
							'transactioncostcentreid',
							'matactivoption',
							'matactivid',
							'transferflag',
							'creditortypeoption',
							'creditortypeid',
							'transactionemployeeoption',
							'transactionemployeeid',
							'lawmattermessageoption',
							'partygroupoption',
							'partygroupid',
							'distributionzerobalanceoption'
    ];

	public function setdateAttribute($value)
	{
		$this->attributes['date'] = $value ? (String)ModelHelper::convertClarionDate($value) : '';
	}

	public function setcreateddateAttribute($value)
	{
		$this->attributes['createddate'] = $value ? (String)ModelHelper::convertClarionDate($value) : '';
	}

}
        
